### ISSUE TITLE
Additional resources

### ISSUE THREAD

**Issue by Crell** [darkwood-com/flow#21]
I was amused and delighted to see a link to one of my videos on the Resources page. :smile: (The Functional PHP video.)

In case you're interested, two more possible resources to include:

A pipe-centric library of utilities: https://github.com/Crell/fp

The very updated version of the talk, now as a book: https://leanpub.com/thinking-functionally-in-php/

If you don't want to include them that's fine, but I figured I'd offer since I was already on the list.  Interesting looking library!

**Comment by matyo91** [comment]
Hi @Crell !

Very thanks for your interest in my library.
In deed, I did get the idea to make this library after having looked at various ressources on the internet.
Why not integrating your library, I must have a look as I provide the `pipe` function in a dedicated `Rail` interface `https://github.com/darkwood-fr/railway-fbp/blob/1.x/packages/php/src/RailInterface.php` and then be a dedicated Rail integration.

I very appreciate feed back like yours and hope get more !
In this case I could add more functionalities depending on needs.

**Comment by Crell** [comment]
I'm not really sure I follow.  What would integrating Crell/fp with Railway look like?  Crell/fp is just a collection of small utilities built to emulate a pipe operator `|>`.  It's not really a full monad, nor was it intended as such.

**Comment by matyo91** [comment]
Ok, you mean integrating your links into the documentation ressources section !

First I think this was about integrating your `pipe` library as a concrete Rail implementation.

I have updated the doc to a dedicated [PR](https://github.com/darkwood-fr/railway-fbp/pull/22).
And merged ! 🚀

Result can be read here : https://darkwood-fr.github.io/railway-fbp/docs/getting-started/ressources/

**Comment by Crell** [comment]
Ah, yes, I just meant the resource page.  Thanks!
